Fix build issues with GCC 14
GCC 14 enables -Wincompatible-pointer-types by default thus resulting in
build error such as:
exo-icon-view.c:2686:27: error: assignment to GdkWindow {aka struct _GdkWindow } from incompatible pointer type GObject {aka struct _GObject } [-Wincompatible-pointer-types]

Much of the code changes are borrowed from older code segments.

First reported on Gentoo linux, for more reference please bug:
https://bugs.gentoo.org/928492

Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>